name: traffic-flow-environment
channels: [conda-forge]
dependencies:
  - python=3.10
  - ipykernel=6.29.5
  - ipython>=8.12,<9
  - nbformat>=5.10,<6
  - plotly>=5.19,<6
  - numpy=1.26.4
  - pandas=2.2.2
  - pyarrow=16.1.0
  - scipy=1.11.4
  - scikit-learn=1.4.0
  - xgboost=2.0.3
  - joblib=1.4.2
  - flask=2.3.3
  - fastparquet=2024.5.0
  - gunicorn=21.2.0
  - requests>=2.31,<3 
  - seaborn>=0.13,<0.14
  - filelock 
  - tqdm>=4.66,<5
  - pykalman
  - pip:
        # Install YOUR package (editable local dev)
        - -e .

        # TensorFlow per platform (pip evaluates these markers):
        # Apple Silicon (M1/M2/M3)
        - "tensorflow-macos==2.15.*; platform_system == 'Darwin' and platform_machine == 'arm64'"

        # macOS Intel (TF >2.10 is not supported; pin to 2.10.x CPU)
        - "tensorflow==2.10.*; platform_system == 'Darwin' and platform_machine == 'x86_64'"

        # Linux (CPU default). If you need GPU, see note below.
        - "tensorflow==2.15.*; platform_system == 'Linux'"

        # Windows (CPU default)
        - "tensorflow==2.15.*; platform_system == 'Windows' and platform_machine == 'AMD64'"