name: tf-clean
channels: [conda-forge]
dependencies:
  - python=3.10
  - ipykernel=6.29.5
  - ipython>=8.12,<9
  - nbformat>=5.10,<6
  - plotly>=5.19,<6
  - numpy=1.26.4
  - pandas=2.2.2
  - pyarrow=16.1.0
  - scipy=1.11.4
  - scikit-learn=1.4.0
  - xgboost=2.0.3
  - joblib=1.4.2
  - flask=2.3.3
  - fastparquet=2024.5.0
  - gunicorn=21.2.0
  - requests>=2.31,<3 
  - seaborn>=0.13,<0.14
  - pip:
      # Linux (NVIDIA): TF with bundled CUDA/cuDNN
      - 'tensorflow[and-cuda]>=2.16,<2.19; platform_system == "Linux"'
      # macOS (both Apple silicon & Intel): base TF
      - 'tensorflow>=2.16,<2.19; platform_system == "Darwin"'
      # macOS GPU via Metal plugin
      - 'tensorflow-metal>=1.1; platform_system == "Darwin"'